<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(VemryxOneWindowsTargetFramework)</TargetFramework>
    <AssemblyName>FiveMCleaner.UpdateRuntime</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <ProjectReference Include="..\Vemryx.One.Contracts\Vemryx.One.Contracts.csproj" />
  </ItemGroup>
</Project>
