<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RalvenWindowsTargetFramework)</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>Ralven.ReleaseTool</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ralven.UpdateRuntime/Ralven.UpdateRuntime.csproj" />
  </ItemGroup>
</Project>
