<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(FiveMCleanerWindowsTargetFramework)</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>../FiveMCleaner.App/Assets/VemryxOne.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>FiveMCleaner.Updater</AssemblyName>
    <RootNamespace>FiveMCleaner.Updater</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FiveMCleaner.UpdateRuntime/FiveMCleaner.UpdateRuntime.csproj" />
  </ItemGroup>
</Project>
