using Vemryx.One.Contracts;

namespace Vemryx.One.Core.Catalog;

public sealed partial class ActionCatalog
{
    private static IReadOnlyList<OptimizationActionDefinition> CreateHardwareDiagnosisActions()
    {
        return
        [
            Define(
                OptimizationActionIds.GuidePerformanceDiagnostics,
                "Orientar diagnóstico de desempenho",
                "Aponta os comandos oficiais do FiveM (cl_drawfps, cl_drawperf, netgraph) para medir FPS e rede dentro do próprio jogo.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ensina a medir o desempenho real usando ferramentas oficiais, sem prometer um número específico.",
                ActionOptionGate.Always,
                detectionSummary: "Não lê nada do sistema; apresenta uma orientação fixa baseada na documentação oficial do FiveM.",
                confirmationSummary: "Sempre é concluída com a mensagem de orientação.",
                undoSummary: "Somente leitura: não há nada para desfazer.",
                riskLimitations: "Não injeta overlay nem mede FPS pelo aplicativo; a medição é feita pelo próprio FiveM."),
            Define(
                OptimizationActionIds.DiagnoseNetworkHealth,
                "Diagnosticar saúde da rede local",
                "Lê contadores de pacotes descartados e com erro das placas de rede ativas, sem enviar tráfego a nenhum servidor.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Indica sinais locais de instabilidade de rede; não mede ping nem jitter até o servidor do FiveM.",
                ActionOptionGate.Always,
                detectionSummary: "Lê estatísticas já coletadas pelo Windows para as placas de rede ativas (pacotes descartados/com erro).",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não envia nem recebe tráfego de rede.",
                riskLimitations: "Não substitui netgraph/cl_drawperf do próprio FiveM para latência real até o servidor."),
            Define(
                OptimizationActionIds.DiagnoseThermalThrottling,
                "Diagnosticar temperatura e throttling",
                "Tenta ler a zona térmica ACPI exposta pelo Windows; a maioria das placas-mãe não expõe esse dado sem software do fabricante, e isso é informado com honestidade.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Quando disponível, ajuda a identificar quedas de desempenho por superaquecimento.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta MSAcpi_ThermalZoneTemperature (WMI) e valida se o valor está numa faixa plausível.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não há nada para desfazer.",
                riskLimitations: "Sem software do fabricante da placa-mãe/GPU, a maioria dos sistemas não expõe essa leitura; o app nunca inventa um valor."),
            Define(
                OptimizationActionIds.DiagnosePagefileCommit,
                "Diagnosticar pagefile e memória committed",
                "Lê o tamanho total e disponível do arquivo de paginação para avisar quando o sistema está perto do limite de commit, sem redimensionar nada.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Sinaliza risco de lentidão por paginação excessiva antes que ele afete a sessão.",
                ActionOptionGate.Always,
                detectionSummary: "Lê o total e o disponível do arquivo de paginação do Windows (GlobalMemoryStatusEx).",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: nunca redimensiona ou desativa o pagefile.",
                riskLimitations: "O Windows já gerencia o pagefile automaticamente na maioria dos sistemas; o app não altera esse gerenciamento."),
            Define(
                OptimizationActionIds.DiagnoseCacheIntegrity,
                "Diagnosticar integridade do índice de cache",
                "Verifica se o índice de cache do FiveM (content_index.xml) existe e está bem formado, recomendando o reparo já existente quando necessário.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Ajuda a decidir quando vale a pena reparar o cache em vez de investigar outra causa.",
                ActionOptionGate.Always,
                detectionSummary: "Tenta abrir e interpretar como XML o content_index.xml de server-cache e server-cache-priv, se existirem.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não repara nem apaga nada; apenas recomenda a ação de reparo de cache já existente.",
                riskLimitations: "A ausência do arquivo não é tratada como corrupção; apenas um arquivo presente e ilegível gera aviso."),
            Define(
                OptimizationActionIds.DetectGpuVendor,
                "Detectar fabricante da GPU",
                "Identifica o fabricante (NVIDIA, AMD ou Intel) das GPUs detectadas e orienta o ajuste manual no painel oficial do fabricante, sem escrever nenhum perfil de driver.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Facilita encontrar o painel de controle correto sem o app tocar em perfis de driver.",
                ActionOptionGate.Always,
                detectionSummary: "Lê a descrição do driver de vídeo já usada no diagnóstico de hardware do aplicativo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não abre, escreve nem reseta nenhum perfil NVIDIA/AMD/Intel.",
                riskLimitations: "Não sobrescreve perfil de GPU nem força shader cache; isso é proibido pelo modelo de segurança do produto."),
            Define(
                OptimizationActionIds.DiagnoseCpuDetails,
                "Diagnosticar núcleos, threads e frequência da CPU",
                "Lê a quantidade de núcleos físicos, threads lógicas e a frequência atual/máxima da CPU via WMI padrão.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a entender a capacidade de CPU disponível e sinais de queda de frequência.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_Processor (WMI) por núcleos, threads e clock atual/máximo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera afinidade, prioridade nem frequência.",
                riskLimitations: "Não lê temperatura nem sensores por núcleo; isso exigiria driver de terceiros, fora do escopo do produto."),
            Define(
                OptimizationActionIds.DiagnoseGpuDetails,
                "Diagnosticar VRAM e tipo da GPU",
                "Lê a VRAM reportada pelo driver e estima se cada GPU detectada é integrada ou dedicada, sem escrever nenhum perfil.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar se o FiveM está usando a GPU dedicada e se há VRAM suficiente.",
                ActionOptionGate.Always,
                detectionSummary: "Lê HardwareInformation.qwMemorySize e a descrição do driver no registro de vídeo já usado pelo app.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não escreve nenhum valor de registro ou perfil de driver.",
                riskLimitations: "A classificação integrada/dedicada é uma estimativa por nome do driver, não uma leitura de hardware garantida."),
            Define(
                OptimizationActionIds.DiagnoseRamDetails,
                "Diagnosticar frequência, canais e XMP/EXPO da RAM",
                "Lê a frequência configurada e nominal de cada módulo de RAM, estimando single-channel e se XMP/EXPO parece desativado.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar memória rodando abaixo do potencial nominal.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_PhysicalMemory (WMI) por capacidade, ConfiguredClockSpeed e Speed de cada módulo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera BIOS, perfil de memória nem frequência.",
                riskLimitations: "Canal e XMP/EXPO são estimativas heurísticas; a confirmação exata depende da BIOS/UEFI."),
            Define(
                OptimizationActionIds.DiagnoseStorageHealth,
                "Diagnosticar tipo e saúde das unidades",
                "Identifica HDD, SSD ou NVMe de cada unidade física e lê o status de saúde preditiva (SMART/NVMe Health), sem reparar nada.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Alerta cedo sobre discos com risco de falha ou tipo inadequado para o FiveM.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta MSFT_PhysicalDisk (Storage Management API), que cobre SATA S.M.A.R.T. e NVMe Health sem driver adicional.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não repara, formata nem move dados.",
                riskLimitations: "Reporta todas as unidades físicas detectadas; não afirma com certeza qual delas hospeda o FiveM."),
            Define(
                OptimizationActionIds.DiagnoseDriverVersions,
                "Diagnosticar build do Windows e versões de driver",
                "Lê o build exato do Windows e as versões dos drivers de vídeo, rede, áudio e chipset (quando identificável).",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar drivers desatualizados como causa de instabilidade.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_PnPSignedDriver (WMI) agrupado por classe de dispositivo, mais Environment.OSVersion para o build.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não instala, atualiza nem reverte nenhum driver.",
                riskLimitations: "O driver de chipset é identificado por heurística de nome; nem todo fabricante o expõe como classe própria."),
            Define(
                OptimizationActionIds.DiagnoseDisplayConfiguration,
                "Diagnosticar resolução, taxa de atualização e HAGS",
                "Compara a taxa de atualização configurada com a máxima suportada na resolução atual e lê o estado do HAGS.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Evita que o monitor fique configurado abaixo da taxa de atualização que suporta.",
                ActionOptionGate.Always,
                detectionSummary: "Usa EnumDisplaySettings (Win32) para o modo atual/máximo e o registro de GraphicsDrivers para HwSchMode.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera resolução, taxa de atualização nem HAGS.",
                riskLimitations: "G-SYNC/FreeSync/VRR não têm API pública sem driver do fabricante; o app informa isso em vez de adivinhar."),
            Define(
                OptimizationActionIds.DiagnoseSessionSettings,
                "Diagnosticar Modo de Jogo, tela cheia e plano de energia",
                "Lê o estado atual do Modo de Jogo, das otimizações para tela cheia e do plano de energia ativo, sem alterar nada.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Mostra o estado real antes de decidir se vale a pena aplicar as ações correspondentes.",
                ActionOptionGate.Always,
                detectionSummary: "Lê os mesmos valores de registro usados pelas ações de Modo de Jogo/captura, mais o esquema de energia ativo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não ativa nem desativa nada.",
                riskLimitations: "Apenas relata o estado atual; para aplicar mudanças, use as ações correspondentes do perfil."),
            Define(
                OptimizationActionIds.DiagnoseThrottlingSignal,
                "Diagnosticar sinais combinados de throttling",
                "Combina queda de frequência sob carga, eventos de erro de hardware (WHEA) e temperatura disponível para indicar 'possível throttling', sem sensor direto por núcleo.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Sinaliza possível throttling mesmo quando não há sensor de temperatura confiável disponível.",
                ActionOptionGate.Always,
                detectionSummary: "Combina Win32_Processor (clock), uma amostra de uso de CPU, eventos Kernel-WHEA recentes e a zona térmica ACPI, quando disponível.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera plano de energia, afinidade nem prioridade.",
                riskLimitations: "Sem sensor direto por núcleo, o resultado é sempre apresentado como 'possível', nunca como certeza."),
            Define(
                OptimizationActionIds.DiagnoseResourceUsage,
                "Diagnosticar uso atual de CPU, disco, GPU e rede",
                "Faz uma leitura instantânea (não uma média) do uso de CPU, disco, GPU (quando disponível) e throughput de rede.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Dá contexto imediato de carga do sistema no momento da otimização.",
                ActionOptionGate.Always,
                detectionSummary: "Usa PerformanceCounter para CPU/disco/GPU (categoria nativa 'GPU Engine') e contadores de interface de rede para throughput.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não define prioridade nem afinidade de processos.",
                riskLimitations: "É uma amostra curta (~300 ms), não uma média sustentada; a GPU pode não estar disponível em todo hardware."),
            Define(
                OptimizationActionIds.DiagnosePciLink,
                "Diagnosticar link PCIe da GPU",
                "Tenta ler a largura e velocidade atual/máxima do link PCIe de cada GPU via propriedades de dispositivo do Windows, sem driver de terceiros.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar uma GPU rodando num slot ou modo PCIe mais lento que o esperado.",
                ActionOptionGate.Always,
                detectionSummary: "Usa CM_Get_DevNode_Property (cfgmgr32) com os DEVPKEYs padrão de link PCIe do Windows.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não reconfigura o barramento nem o slot.",
                riskLimitations: "Nem todo driver/placa-mãe expõe essas propriedades; quando ausente, o app informa isso em vez de adivinhar."),
            Define(
                OptimizationActionIds.DiagnoseHardwareStability,
                "Diagnosticar idade da BIOS e estabilidade de hardware",
                "Lê a data de lançamento da BIOS e eventos recentes de erro de hardware (WHEA) no Log de Eventos do Windows.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a identificar BIOS desatualizada ou instabilidade de hardware como causa raiz.",
                ActionOptionGate.Always,
                detectionSummary: "Consulta Win32_BIOS (WMI) e eventos da fonte Microsoft-Windows-Kernel-WHEA no log System.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não atualiza BIOS nem limpa o log de eventos.",
                riskLimitations: "Resizable BAR/Above 4G/Smart Access Memory não são detectáveis de forma confiável sem ferramenta do fabricante; o app informa essa limitação em vez de adivinhar."),
            Define(
                OptimizationActionIds.ClassifyBottleneck,
                "Classificar tipo provável de gargalo",
                "Combina uso de CPU/GPU/disco/rede, memória, temperatura e o processo que mais consome CPU para apontar o recurso mais provavelmente limitante no momento.",
                ActionCategory.Safety,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Ajuda a decidir qual ajuste vale mais a pena antes de tentar várias mudanças às cegas.",
                ActionOptionGate.Always,
                detectionSummary: "Combina as leituras já feitas por outros diagnósticos (uso de recursos, temperatura, rede, memória) com o processo de maior uso de CPU no momento (Win32_PerfFormattedData_PerfProc_Process).",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não encerra nem prioriza nenhum processo.",
                riskLimitations: "É uma classificação por eliminação a partir de sinais locais; 'servidor limitado' é a conclusão quando nenhum sinal local se destaca, não uma medição direta do servidor."),
            Define(
                OptimizationActionIds.DiagnoseCacheStorage,
                "Diagnosticar tamanho e integridade do cache do FiveM",
                "Mede o tamanho total e por categoria do cache do FiveM Legacy (server-cache, server-cache-priv, NUI storage, logs, diagnósticos) e sinaliza arquivos bloqueados por outro processo, sem apagar nada.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Ajuda a decidir se vale a pena reparar o cache antes de executar a limpeza.",
                ActionOptionGate.Always,
                detectionSummary: "Percorre as pastas conhecidas de cache/dados do FiveM Legacy somando o tamanho de cada uma e tentando abrir cada arquivo com acesso exclusivo para detectar bloqueio por outro processo.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não apaga nem move nenhum arquivo.",
                riskLimitations: "A detecção de bloqueio é um teste de abertura exclusiva no momento da leitura; um arquivo pode ficar bloqueado ou livre segundos depois."),
            Define(
                OptimizationActionIds.DiagnoseInstallationHealth,
                "Diagnosticar saúde da instalação do FiveM",
                "Verifica instalações duplicadas, permissão de escrita na pasta de dados, sincronização por OneDrive e espaço livre em disco, sem alterar nada.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Aponta causas comuns de instabilidade relacionadas à própria instalação, antes de suspeitar do servidor ou do hardware.",
                ActionOptionGate.Always,
                detectionSummary: "Compara candidatos de instalação conhecidos (registro e CitizenFX.ini), testa escrita na pasta de dados, compara o caminho com a pasta sincronizada do OneDrive e lê o espaço livre da unidade da instalação.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não apaga, move nem reinstala nada.",
                riskLimitations: "A detecção de instalação duplicada é heurística por caminho conhecido; instalações em locais não convencionais podem não ser encontradas."),
            Define(
                OptimizationActionIds.DiagnoseCrashPatterns,
                "Diagnosticar padrões recorrentes de erro e streaming",
                "Procura códigos de erro reconhecíveis nos nomes dos crash dumps recentes e palavras-chave de erro de streaming (texturas, modelos, mapas) no log mais recente, sem apagar nada.",
                ActionCategory.Storage,
                ActionRisk.Informational,
                ActionReversibility.ReadOnly,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Ajuda a identificar um padrão recorrente em vez de tratar cada travamento como um evento isolado.",
                ActionOptionGate.Always,
                detectionSummary: "Lê os nomes dos arquivos de dump recentes em busca de códigos de erro conhecidos e faz busca textual por palavras-chave de streaming no log mais recente do FiveM.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não abre, remove nem envia nenhum dump.",
                riskLimitations: "É uma busca textual por padrões conhecidos, não uma análise de despejo de memória; um padrão ausente não garante ausência do problema.")
        ];
    }
}
