<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(VemryxOneWindowsTargetFramework)</TargetFramework>
    <RootNamespace>Vemryx.One.Windows</RootNamespace>
    <AssemblyName>FiveMCleaner.Windows</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" />
    <ProjectReference Include="../Vemryx.One.Contracts/Vemryx.One.Contracts.csproj" />
    <ProjectReference Include="../Vemryx.One.Core/Vemryx.One.Core.csproj" />
  </ItemGroup>
</Project>
