<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(FiveMCleanerWindowsTargetFramework)</TargetFramework>
    <RootNamespace>FiveMCleaner.Broker</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../FiveMCleaner.App/Assets/VemryxOne.ico</ApplicationIcon>
    <AssemblyName>FiveMCleaner.Broker</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FiveMCleaner.Contracts/FiveMCleaner.Contracts.csproj" />
    <ProjectReference Include="../FiveMCleaner.Core/FiveMCleaner.Core.csproj" />
    <ProjectReference Include="../FiveMCleaner.Windows/FiveMCleaner.Windows.csproj" />
  </ItemGroup>
  <Target Name="GetBrokerOutputDirectory" DependsOnTargets="Build" Returns="@(_BrokerOutputDirectory)">
    <ItemGroup>
      <_BrokerOutputDirectory Include="$(TargetDir)" />
    </ItemGroup>
  </Target>
</Project>
