<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(VemryxOneWindowsTargetFramework)</TargetFramework>
    <RootNamespace>Vemryx.One.Broker</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../Vemryx.One.App/Assets/VemryxOne.ico</ApplicationIcon>
    <AssemblyName>FiveMCleaner.Broker</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Vemryx.One.Contracts/Vemryx.One.Contracts.csproj" />
    <ProjectReference Include="../Vemryx.One.Core/Vemryx.One.Core.csproj" />
    <ProjectReference Include="../Vemryx.One.Windows/Vemryx.One.Windows.csproj" />
  </ItemGroup>
  <Target Name="GetBrokerOutputDirectory" DependsOnTargets="Build" Returns="@(_BrokerOutputDirectory)">
    <ItemGroup>
      <_BrokerOutputDirectory Include="$(TargetDir)" />
    </ItemGroup>
  </Target>
</Project>
