<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(VemryxOneTargetFramework)</TargetFramework>
    <RootNamespace>Vemryx.One.Core</RootNamespace>
    <AssemblyName>FiveMCleaner.Core</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Vemryx.One.Contracts/Vemryx.One.Contracts.csproj" />
  </ItemGroup>
</Project>
