using Ralven.Contracts;

namespace Ralven.Core.Catalog;

public sealed partial class ActionCatalog
{
    private static IReadOnlyList<OptimizationActionDefinition> CreateGamingGuidanceActions()
    {
        return
        [
            Define(
                OptimizationActionIds.DiagnoseGpuPreferenceMismatch,
                "Diagnosticar preferência de GPU em notebooks com duas GPUs",
                "Compara a detecção de GPU integrada + dedicada com a preferência configurada nas preferências gráficas do Windows para o FiveM, sem alterar nada.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Evita que o jogo rode na GPU integrada por engano em notebooks híbridos, sem nunca alterar nada sozinho.",
                ActionOptionGate.Always,
                detectionSummary: "Lê os adaptadores de vídeo do registro e a preferência de GPU já configurada para o FiveM.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera a preferência de GPU.",
                riskLimitations: "Não consegue confirmar qual GPU o jogo está de fato usando numa sessão ao vivo; a verificação é limitada à configuração registrada."),
            Define(
                OptimizationActionIds.ToggleFullscreenOptimizations,
                "Testar desativar otimizações de tela cheia",
                "Ativa ou desativa (alternando) a sinalização 'Desativar otimizações de tela cheia' para FiveM e GTA V, como teste de compatibilidade opt-in. Nunca faz parte de perfis automáticos além do Agressivo.",
                ActionCategory.WindowsGaming,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AggressiveOnly,
                requiresFiveMStopped: false,
                progressWeight: 3,
                expectedImpact: "Serve para testar se desativar Fullscreen Optimizations melhora algo neste hardware específico; a Microsoft afirma que, na média, não há ganho.",
                ActionOptionGate.ToggleFullscreenOptimizations,
                detectionSummary: "Lê a sinalização de compatibilidade existente para os executáveis do FiveM/GTA V.",
                confirmationSummary: "Confirma que apenas a sinalização de tela cheia foi alternada, preservando outras sinalizações de compatibilidade já presentes.",
                undoSummary: "Totalmente reversível: o valor anterior exato é restaurado no rollback.",
                riskLimitations: "Mecanismo baseado em convenção observada da chave AppCompatFlags\\Layers, não em documentação oficial da Microsoft; compare o resultado você mesmo e reverta se não notar melhora."),
            Define(
                OptimizationActionIds.ToggleHags,
                "Testar Hardware-Accelerated GPU Scheduling (HAGS)",
                "Alterna o HAGS entre ativado e o padrão do Windows, como teste de compatibilidade opt-in. Nunca faz parte de perfis automáticos além do Agressivo.",
                ActionCategory.WindowsGaming,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.Administrator,
                AggressiveOnly,
                requiresFiveMStopped: false,
                progressWeight: 3,
                requiresRestart: true,
                expectedImpact: "Serve para testar se o outro estado do HAGS melhora a consistência de frametime neste hardware; nunca é um aumento garantido de FPS.",
                optionGate: ActionOptionGate.ToggleHags,
                detectionSummary: "Lê o valor atual de HwSchMode no registro dos drivers de vídeo.",
                confirmationSummary: "Confirma que o valor foi alternado; exige reiniciar o Windows para ter efeito.",
                undoSummary: "Totalmente reversível: o valor anterior é restaurado no rollback (também exige reinício para valer).",
                riskLimitations: "O resultado varia por combinação de GPU/driver; a Microsoft não garante ganho de FPS com HAGS ativado ou desativado.",
                attemptWithoutElevationFirst: true),
            Define(
                OptimizationActionIds.GuideGSync,
                "Orientar sobre G-SYNC/FreeSync/VRR",
                "Orienta como conferir e ativar o G-SYNC (NVIDIA) ou FreeSync (AMD) pelo painel oficial do fabricante ou pelo monitor, e sugere um limite de FPS compatível com a faixa variável, sem alterar nada.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda o usuário a ativar G-SYNC/FreeSync corretamente e a escolher um limite de FPS compatível, sem prometer o que este app não pode garantir.",
                ActionOptionGate.Always,
                detectionSummary: "Lê a taxa de atualização máxima detectada na resolução atual e o fabricante da GPU.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não ativa nem desativa G-SYNC/FreeSync/VRR.",
                riskLimitations: "Não existe API pública para confirmar ou ativar G-SYNC/FreeSync/VRR; a orientação é best-effort, nunca um fato garantido."),
            Define(
                OptimizationActionIds.GuideDriverReinstall,
                "Orientar reinstalação limpa do driver de vídeo",
                "Mostra o passo a passo oficial de reinstalação limpa do driver de vídeo (DDU + instalador oficial) quando há suspeita de corrupção. Nunca baixa, instala ou remove nada sozinho. Nunca faz parte de perfis automáticos.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda a resolver problemas causados por instalação corrompida do driver de vídeo, com os passos oficiais do fabricante.",
                ActionOptionGate.GuideDriverReinstall,
                detectionSummary: "Nenhuma detecção automática de corrupção; é acionado manualmente pelo usuário.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não baixa, instala nem remove nenhum driver.",
                riskLimitations: "É orientação, não reparo automático; reinstalar o driver errado ou interromper a instalação pode deixar o computador sem saída de vídeo -- siga os passos com cuidado."),
            Define(
                OptimizationActionIds.DiagnoseHybridLaptop,
                "Diagnosticar notebook híbrido/gaming",
                "Verifica se o notebook está na bateria ou com Economia de Energia ativa e detecta utilitários conhecidos de troca de GPU/desempenho do fabricante (Armoury Crate, MSI Center, Lenovo Vantage, etc.), sem alterar nada.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 2,
                expectedImpact: "Ajuda o usuário a identificar quando o notebook não está no melhor estado de energia/GPU para jogar, e para qual utilitário do fabricante recorrer.",
                ActionOptionGate.Always,
                detectionSummary: "Lê o estado de energia (CA/bateria, Economia de Energia) e a lista de utilitários de fabricante instalados.",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera energia, GPU nem instala/remove nada.",
                riskLimitations: "Não controla MUX switch nem BIOS por métodos genéricos não documentados; detectar o utilitário do fabricante instalado não confirma que o notebook tem MUX switch ou GPU dedicada."),
            Define(
                OptimizationActionIds.GuideMousePollingRate,
                "Orientar sobre polling rate do mouse",
                "Quando a CPU está sob carga alta, orienta testar reduzir mouses configurados para 4000/8000 Hz de polling para 1000 Hz, sem alterar nada.",
                ActionCategory.WindowsGaming,
                ActionRisk.Informational,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 1,
                expectedImpact: "Orienta um teste de baixo risco (reduzir polling rate) quando a CPU já está sob carga alta, sem prometer que resolve stutter.",
                ActionOptionGate.Always,
                detectionSummary: "Lê o uso atual de CPU (mesma medição já usada nos diagnósticos de recursos existentes).",
                confirmationSummary: "Sempre é concluída com uma mensagem informativa; nunca falha por si só.",
                undoSummary: "Somente leitura: não altera nenhuma configuração de mouse ou de sistema.",
                riskLimitations: "Não lê a taxa de polling real do mouse (não há API pública documentada para isso) nem correlaciona stutter com movimento do mouse em tempo real; a orientação é sempre condicionada à carga de CPU observada no momento do diagnóstico.")
        ];
    }
}
