using Ralven.Contracts;

namespace Ralven.Core.Catalog;

public sealed partial class ActionCatalog
{
    private static IReadOnlyList<OptimizationActionDefinition> CreateCleanupActions()
    {
        return
        [
            Define(
                OptimizationActionIds.CleanUserTemporaryFiles,
                "Limpar temporários antigos",
                "Remove somente arquivos temporários do usuário que ultrapassaram o período de retenção configurado.",
                ActionCategory.Storage,
                ActionRisk.Low,
                ActionReversibility.Irreversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 18,
                expectedImpact: "Libera espaço; não promete melhora direta de desempenho.",
                ActionOptionGate.CleanUserTemporaryFiles,
                detectionSummary: "Percorre a pasta Temp do usuário buscando arquivos além do período de retenção.",
                confirmationSummary: "Confirma que os arquivos antigos selecionados não existem mais após a limpeza.",
                undoSummary: "Irreversível: arquivos temporários antigos não são preservados em quarentena.",
                riskLimitations: "Remove apenas arquivos antigos do próprio usuário; nunca toca em pastas do sistema."),
            Define(
                OptimizationActionIds.PruneLegacyCrashDumps,
                "Remover diagnósticos antigos",
                "Remove dumps e logs antigos do FiveM Legacy, preservando os arquivos dentro do período de retenção.",
                ActionCategory.Storage,
                ActionRisk.Low,
                ActionReversibility.Irreversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 12,
                expectedImpact: "Libera espaço ocupado por diagnósticos antigos.",
                ActionOptionGate.RemoveOldFiveMCrashDumps,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lista dumps e logs do FiveM mais antigos que o período de retenção.",
                confirmationSummary: "Confirma que os diagnósticos antigos foram removidos e os recentes preservados.",
                undoSummary: "Irreversível: diagnósticos antigos não são copiados para o journal.",
                riskLimitations: "Dumps podem ser úteis para suporte; apenas os fora do período de retenção são removidos."),
            Define(
                OptimizationActionIds.RepairLegacyServerCache,
                "Reparar cache de servidores",
                "Remove somente caches regeneráveis de conteúdo de servidores do FiveM Legacy.",
                ActionCategory.Storage,
                ActionRisk.Moderate,
                ActionReversibility.RebuildableData,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 30,
                expectedImpact: "Pode corrigir corrupção ou liberar espaço; o primeiro carregamento ficará mais lento.",
                ActionOptionGate.RepairLegacyServerCache,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Mede o tamanho de server-cache e server-cache-priv sob a instalação do FiveM.",
                confirmationSummary: "Confirma que apenas os caches regeneráveis foram removidos.",
                undoSummary: "Dados regeneráveis: o FiveM baixa o conteúdo novamente no próximo acesso ao servidor.",
                riskLimitations: "O primeiro carregamento fica mais lento; clipes antigos do Rockstar Editor podem deixar de funcionar."),
            Define(
                OptimizationActionIds.TerminateStuckFiveMProcess,
                "Encerrar processo travado do FiveM",
                "Encerra um processo do FiveM comprovadamente travado e sem resposta. Isso pode liberar arquivos ainda mantidos por essa instância, mas nunca faz parte de perfis automáticos.",
                ActionCategory.Storage,
                ActionRisk.Moderate,
                ActionReversibility.Irreversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: false,
                progressWeight: 5,
                expectedImpact: "Pode liberar arquivos mantidos por uma instância travada do FiveM sem exigir reinício manual do Windows.",
                ActionOptionGate.TerminateStuckFiveMProcess,
                detectionSummary: "Verifica se existe processo cuja imagem pertence à instalação do FiveM com Responding=false (não responde a mensagens da interface).",
                confirmationSummary: "Só encerra o processo depois de confirmar que ele não responde; se estiver respondendo normalmente, a ação não faz nada.",
                undoSummary: "Irreversível: um processo encerrado não pode ser restaurado ao seu estado anterior.",
                riskLimitations: "Encerra apenas processos cuja imagem executável pertence à pasta de instalação do FiveM; nunca processos de terceiros, do jogo GTA V ou do sistema. Qualquer trabalho não salvo dentro desse processo travado é perdido."),
            Define(
                OptimizationActionIds.RecreateFiveMLocalData,
                "Recriar dados locais do FiveM",
                "Remove e recria as pastas de dados regeneráveis do FiveM Legacy (server-cache, server-cache-priv, logs, crashes) preservando game-storage, NUI storage, ipfs, CitizenFX.ini e plugins, com backup em quarentena.",
                ActionCategory.Storage,
                ActionRisk.High,
                ActionReversibility.RebuildableData,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 25,
                expectedImpact: "Repara uma instalação com dados regeneráveis corrompidos; o primeiro carregamento após a recriação fica mais lento.",
                ActionOptionGate.RecreateFiveMLocalData,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Confirma que o FiveM está fechado e lista os arquivos dentro das pastas regeneráveis conhecidas (nunca as protegidas por docs/safety.md).",
                confirmationSummary: "Move os arquivos regeneráveis para quarentena antes de confirmar; nada protegido é tocado.",
                undoSummary: "Dados regeneráveis: reversível via quarentena até a confirmação final da otimização; depois disso, o FiveM baixa o conteúdo novamente.",
                riskLimitations: "Não é uma reinstalação do FiveM nem baixa/executa nenhum instalador; apenas recria as pastas de dados já sancionadas para limpeza condicionada em docs/safety.md."),
            Define(
                OptimizationActionIds.RepairStaleAuthData,
                "Reparar dados de entitlement corrompidos",
                "Remove ros_id.dat e a pasta de entitlements digitais apenas quando um padrão de erro de inicialização relacionado a entitlement é detectado no log mais recente, com backup em quarentena e confirmação a cada execução.",
                ActionCategory.Storage,
                ActionRisk.High,
                ActionReversibility.RebuildableData,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 8,
                expectedImpact: "Corrige falhas específicas de inicialização causadas por dados de entitlement corrompidos, exigindo novo login no próximo início.",
                ActionOptionGate.RepairStaleAuthData,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê o log mais recente do FiveM em busca de um padrão de erro de entitlement/autenticação já conhecido antes de tocar em qualquer arquivo.",
                confirmationSummary: "Só remove ros_id.dat e a pasta de entitlements quando o padrão de erro foi encontrado; caso contrário, não faz nada.",
                undoSummary: "Reversível via quarentena até a confirmação final da otimização; depois disso, o FiveM solicita novo login para regenerar os dados.",
                riskLimitations: "Ação de exceção documentada em docs/safety.md: ros_id.dat e entitlements normalmente nunca são removidos automaticamente; esta ação só existe para o cenário específico de erro detectado, nunca em perfis automáticos, e sempre em quarentena reversível.",
                version: 2)
        ];
    }
}
