using Ralven.Contracts;

namespace Ralven.Core.Catalog;

public sealed partial class ActionCatalog
{
    private static IReadOnlyList<OptimizationActionDefinition> CreateGraphicsPresetActions()
    {
        return
        [
            Define(
                OptimizationActionIds.ApplyLightLegacyGraphics,
                "Ajustar gráficos leves do FiveM",
                "Desliga apenas antialiasing de maior custo no arquivo existente do FiveM, com backup.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Light],
                requiresFiveMStopped: true,
                progressWeight: 7,
                expectedImpact: "Remove custos altos preservando texturas, resolução e a maior parte da qualidade visual.",
                ActionOptionGate.ApplyLegacyGraphicsPreset,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê as opções existentes de gta5_settings.xml do FiveM.",
                confirmationSummary: "Confirma que apenas as opções caras foram ajustadas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Só altera opções já presentes; não distribui um XML genérico."),
            Define(
                OptimizationActionIds.ApplyBalancedLegacyGraphics,
                "Aplicar gráficos equilibrados",
                "Ajusta somente opções existentes do arquivo gráfico do FiveM Legacy e cria backup antes da gravação.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Balanced],
                requiresFiveMStopped: true,
                progressWeight: 12,
                expectedImpact: "Equilibra qualidade visual, uso de GPU e estabilidade de quadros.",
                ActionOptionGate.ApplyLegacyGraphicsPreset,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê as opções existentes de gta5_settings.xml do FiveM.",
                confirmationSummary: "Confirma que os limites equilibrados foram aplicados e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Resultados variam conforme o hardware; só altera opções já presentes."),
            Define(
                OptimizationActionIds.ApplyAggressiveLegacyGraphics,
                "Aplicar gráficos agressivos",
                "Reduz opções gráficas de maior custo no FiveM Legacy e cria backup antes da gravação.",
                ActionCategory.FiveMGraphics,
                ActionRisk.High,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Aggressive],
                requiresFiveMStopped: true,
                progressWeight: 14,
                expectedImpact: "Prioriza FPS e responsividade em vez de qualidade visual.",
                ActionOptionGate.ApplyLegacyGraphicsPreset,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê as opções existentes de gta5_settings.xml do FiveM.",
                confirmationSummary: "Confirma que as opções pesadas foram reduzidas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Reduz qualidade visual de forma perceptível; não força resolução mínima."),
            Define(
                OptimizationActionIds.ApplyLightGtaVGraphics,
                "Ajustar gráficos leves do GTA V",
                "Detecta o settings.xml do GTA V Legacy, reduz somente opções caras já existentes e cria backup.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Light],
                requiresFiveMStopped: true,
                progressWeight: 7,
                expectedImpact: "Preserva resolução e qualidade geral enquanto reduz antialiasing caro.",
                ActionOptionGate.ApplyGtaVGraphicsPreset,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê as opções existentes do settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que apenas as opções caras foram ajustadas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Só altera opções já presentes; não altera resolução, tela ou adaptador."),
            Define(
                OptimizationActionIds.ApplyBalancedGtaVGraphics,
                "Equilibrar gráficos do GTA V",
                "Aplica limites equilibrados somente em opções existentes do settings.xml do GTA V Legacy, com backup.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Balanced],
                requiresFiveMStopped: true,
                progressWeight: 11,
                expectedImpact: "Equilibra qualidade, uso de GPU e estabilidade de quadros também no GTA V base.",
                ActionOptionGate.ApplyGtaVGraphicsPreset,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê as opções existentes do settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que os limites equilibrados foram aplicados e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Resultados variam conforme o hardware; só altera opções já presentes."),
            Define(
                OptimizationActionIds.ApplyAggressiveGtaVGraphics,
                "Priorizar FPS no GTA V",
                "Reduz opções gráficas pesadas do settings.xml do GTA V Legacy sem alterar resolução, tela ou adaptador.",
                ActionCategory.FiveMGraphics,
                ActionRisk.High,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                [OptimizationProfile.Aggressive],
                requiresFiveMStopped: true,
                progressWeight: 13,
                expectedImpact: "Prioriza FPS sem forçar resolução, taxa de atualização, DirectX ou textura mínima.",
                ActionOptionGate.ApplyGtaVGraphicsPreset,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê as opções existentes do settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que as opções pesadas foram reduzidas e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Reduz qualidade visual; não força resolução, taxa de atualização ou textura mínima."),
            Define(
                OptimizationActionIds.ApplyQualityLegacyGraphics,
                "Aplicar preset de qualidade no FiveM",
                "Aumenta somente opções gráficas já existentes no arquivo do FiveM Legacy até um teto seguro, priorizando qualidade visual sem descontrolar o 1% low. Nunca faz parte de perfis automáticos.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 12,
                expectedImpact: "Aumenta a qualidade visual em hardware com folga; pode reduzir FPS em comparação com os presets Equilibrado ou FPS.",
                ActionOptionGate.ApplyQualityGraphicsPreset,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê as opções existentes de gta5_settings.xml do FiveM.",
                confirmationSummary: "Confirma que apenas as opções elevadas foram aumentadas, com um teto que preserva o 1% low, e que o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Só eleva opções já presentes até um teto conservador; não maximiza tudo às cegas, para não sacrificar consistência de quadros."),
            Define(
                OptimizationActionIds.ApplyQualityGtaVGraphics,
                "Aplicar preset de qualidade no GTA V",
                "Aumenta somente opções gráficas já existentes no settings.xml do GTA V Legacy até um teto seguro, priorizando qualidade visual sem descontrolar o 1% low. Nunca faz parte de perfis automáticos.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 11,
                expectedImpact: "Aumenta a qualidade visual em hardware com folga; pode reduzir FPS em comparação com os presets Equilibrado ou FPS.",
                ActionOptionGate.ApplyQualityGraphicsPreset,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê as opções existentes do settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que apenas as opções elevadas foram aumentadas, com um teto que preserva o 1% low, e que o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Só eleva opções já presentes até um teto conservador; não maximiza tudo às cegas, para não sacrificar consistência de quadros."),
            Define(
                OptimizationActionIds.ApplyLegacyDisplayPreferences,
                "Ajustar janela e VSync do FiveM",
                "Define somente o modo de janela (janela comum ou tela cheia) e o VSync do FiveM Legacy, sem tocar em resolução, adaptador de vídeo ou proporção de tela. Nunca faz parte de perfis automáticos.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 5,
                expectedImpact: "Ajusta latência e estabilidade de exibição sem risco de escolher uma resolução não suportada pelo monitor.",
                ActionOptionGate.ApplyDisplayPreferences,
                prerequisites: RequiresFiveMStoppedFirst,
                detectionSummary: "Lê os valores existentes de janela e VSync no arquivo gráfico do FiveM.",
                confirmationSummary: "Confirma que apenas janela e VSync foram alterados e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Não altera resolução, taxa de atualização, adaptador de vídeo nem proporção de tela; esses itens não são ajustados automaticamente pelo produto por exigirem validação individual contra o monitor."),
            Define(
                OptimizationActionIds.ApplyGtaVDisplayPreferences,
                "Ajustar janela e VSync do GTA V",
                "Define somente o modo de janela (janela comum ou tela cheia) e o VSync do GTA V Legacy, sem tocar em resolução, adaptador de vídeo ou proporção de tela. Nunca faz parte de perfis automáticos.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 5,
                expectedImpact: "Ajusta latência e estabilidade de exibição sem risco de escolher uma resolução não suportada pelo monitor.",
                ActionOptionGate.ApplyGtaVDisplayPreferences,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê os valores existentes de janela e VSync no settings.xml do GTA V Legacy.",
                confirmationSummary: "Confirma que apenas janela e VSync foram alterados e o arquivo permanece válido.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Não altera resolução, taxa de atualização, adaptador de vídeo nem proporção de tela; esses itens não são ajustados automaticamente pelo produto por exigirem validação individual contra o monitor."),
            Define(
                OptimizationActionIds.ApplyGtaVGraphicsLaunchParameters,
                "Aplicar parâmetros gráficos de inicialização do GTA V",
                "Escreve no commandline.txt do GTA V standalone os parâmetros oficiais -cityDensity, -anisotropicQualityLevel, -fxaa, -grassQuality, -lodScale e -frameLimit, preservando qualquer outra linha já existente. Nunca faz parte de perfis automáticos.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 6,
                expectedImpact: "Ajusta parâmetros oficiais documentados pela Rockstar sem depender das opções gráficas dentro do jogo.",
                ActionOptionGate.ApplyGtaVGraphicsLaunchParameters,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê o commandline.txt existente (ou trata como vazio, se ausente) e identifica quais das linhas gerenciadas já estão presentes.",
                confirmationSummary: "Confirma que apenas as linhas gerenciadas foram adicionadas/atualizadas e as demais linhas do arquivo foram preservadas.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Só é relevante para o GTA V standalone; o FiveM ignora esse arquivo. Valores usam limites conservadores documentados; a unidade exata de -frameLimit não é confirmada oficialmente."),
            Define(
                OptimizationActionIds.ApplyGtaVDisplayLaunchParameters,
                "Aplicar parâmetros de exibição de inicialização do GTA V",
                "Escreve no commandline.txt do GTA V standalone o modo de tela (-fullscreen/-windowed/-borderless) e, quando escolhida, a versão do DirectX (-DX10/-DX10_1/-DX11). Nunca altera resolução. Nunca faz parte de perfis automáticos.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Low,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 4,
                expectedImpact: "Define modo de tela e versão do DirectX sem risco de escolher uma resolução não suportada pelo monitor.",
                ActionOptionGate.ApplyGtaVDisplayLaunchParameters,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê o commandline.txt existente (ou trata como vazio, se ausente) e identifica o modo de tela/DirectX já configurados.",
                confirmationSummary: "Confirma que apenas as linhas de modo de tela/DirectX foram adicionadas/atualizadas e as demais linhas do arquivo foram preservadas.",
                undoSummary: "Totalmente reversível: o backup do arquivo é restaurado no rollback.",
                riskLimitations: "Não altera -width/-height nem resolução/taxa de atualização; esses itens exigiriam validar a combinação contra os modos suportados pelo monitor, o que o produto ainda não faz de ponta a ponta."),
            Define(
                OptimizationActionIds.ApplyGtaVRepairLaunchParameters,
                "Aplicar parâmetros de reparo de inicialização do GTA V",
                "Escreve no commandline.txt do GTA V standalone parâmetros de reparo temporários (-safemode, -useMinimumSettings, -UseAutoSettings) para diagnosticar um problema específico. Nunca faz parte de perfis automáticos e não deve ficar ativo permanentemente.",
                ActionCategory.FiveMGraphics,
                ActionRisk.Moderate,
                ActionReversibility.FullyReversible,
                RequiredPrivilege.StandardUser,
                AllProfiles,
                requiresFiveMStopped: true,
                progressWeight: 4,
                expectedImpact: "Ajuda a isolar se um problema é causado por configuração gráfica corrompida, usando os próprios parâmetros de reparo oficiais.",
                ActionOptionGate.ApplyGtaVRepairLaunchParameters,
                prerequisites: RequiresGtaVStoppedFirst,
                detectionSummary: "Lê o commandline.txt existente (ou trata como vazio, se ausente) e identifica quais parâmetros de reparo já estão presentes.",
                confirmationSummary: "Confirma que apenas os parâmetros de reparo escolhidos foram adicionados e as demais linhas do arquivo foram preservadas.",
                undoSummary: "Totalmente reversível: use \"Reverter esta otimização\" assim que terminar de diagnosticar, para não deixar o parâmetro de reparo ativo permanentemente.",
                riskLimitations: "É um parâmetro de reparo, não uma otimização diária; deixá-lo ativo indefinidamente pode reduzir a qualidade gráfica sem necessidade.")
        ];
    }
}
