export type Language = "pt" | "en";

export const DOWNLOAD_URL =
  "https://vemryx.com/Ralven/download/";
export const GITHUB_URL = "https://github.com/marquezinii/VemryxOne";
export const DISCORD_URL = "https://discord.gg/bazcuQB9n6";
export const BRAND_HOME_URL = "https://vemryx.com/";
export const ICON_URL = `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/icon.png`;

export const copy = {
  pt: {
    skip: "Pular para o conteúdo",
    languageLabel: "Selecionar idioma",
    navLabel: "Navegação principal",
    highlightsLabel: "Destaques",
    summaryLabel: "Resumo do produto",
    platformsLabel: "Plataformas preservadas",
    nav: {
      profiles: "Perfis",
      howItWorks: "Como funciona",
      safety: "Segurança",
      faq: "Dúvidas",
    },
    headerDownload: "Baixar",
    discordLabel: "Entre no nosso Discord oficial",
    hero: {
      eyebrow: "RALVEN · OTIMIZAÇÃO TRANSPARENTE",
      titleStart: "Mais desempenho.",
      titleAccent: "Menos complicação.",
      body: "Diagnóstico, manutenção e otimização transparente do Windows, com decisões técnicas claras, progresso real, rollback e recursos especializados para FiveM em GTA V Legacy.",
      download: "Download do instalador",
      github: "Ver código no GitHub",
      releaseNote: "Download oficial Vemryx · sem cadastro",
      included: "Runtime incluído",
      windows: "Windows 11 recomendado",
      rollback: "Rollback disponível",
      releaseKicker: "RELEASE OFICIAL",
      releaseTitle: "Instalação simples. Sem dependências extras.",
      releaseBody: "O instalador inclui o runtime necessário e abre a versão estável mais recente, publicada na origem oficial do projeto.",
      releaseLink: "Abrir download seguro",
    },
    preview: {
      label: "PRÉVIA DA INTERFACE",
      appStatus: "Sistema pronto",
      title: "Seu PC, o plano certo",
      subtitle: "Diagnóstico local concluído",
      ringTop: "PRONTO",
      ringBottom: "para otimizar",
      profileLabel: "Perfil selecionado",
      light: "Leve",
      medium: "Médio",
      aggressive: "Agressivo",
      recommended: "RECOMENDADO",
      progressTitle: "Preparando otimização segura",
      progressDetail: "Validando configurações atuais…",
      detectedGpu: "CPU e GPU identificadas",
      detectedGame: "FiveM detectado",
      local: "Processamento local",
    },
    quickFacts: [
      ["01 clique", "para iniciar"],
      ["03 perfis", "com escopos claros"],
      ["Local", "telemetria opcional"],
      ["Reversível", "com snapshots"],
    ],
    profiles: {
      eyebrow: "TRÊS PRIORIDADES, UMA ESCOLHA SIMPLES",
      title: "Escolha o perfil. O app cuida do restante.",
      intro: "Nada de dezenas de caixas confusas. Cada perfil usa um catálogo seguro de ações e só altera o que realmente precisa de ajuste.",
      items: [
        {
          number: "01",
          name: "Leve",
          summary: "Mais suavidade sem sacrificar a aparência.",
          ideal: "Ideal para PCs atuais que já rodam bem.",
          bullets: [
            "Preserva a qualidade visual",
            "Corrige preferências essenciais do Windows",
            "Remove apenas arquivos temporários seguros",
          ],
        },
        {
          number: "02",
          name: "Médio",
          summary: "O melhor equilíbrio entre imagem e resposta.",
          ideal: "Recomendado para a maioria dos jogadores.",
          bullets: [
            "Equilibra sistema, FiveM e GTA V",
            "Prioriza a GPU correta quando necessário",
            "Mantém serviços e proteções críticas",
          ],
          badge: "RECOMENDADO",
        },
        {
          number: "03",
          name: "Agressivo",
          summary: "Prioridade máxima para desempenho.",
          ideal: "Para hardware de entrada ou muito limitado.",
          bullets: [
            "Reduz mais efeitos visuais dispensáveis",
            "Aplica o conjunto de desempenho mais forte",
            "Continua preservando segurança e rollback",
          ],
        },
      ],
      estimateTitle: "Estimativa honesta, baseada no seu PC",
      estimateBody: "O Ralven usa o hardware e o estado detectado para contextualizar o potencial de cada perfil. Quando não existe um benchmark real, ele informa “ganho não medido” — nunca inventa FPS.",
      estimateTag: "SEM NÚMEROS FALSOS",
    },
    process: {
      eyebrow: "SIMPLES POR FORA, CUIDADOSO POR DENTRO",
      title: "Você acompanha tudo. Passo a passo.",
      intro: "A barra de progresso mostra a ação atual, o tempo decorrido e uma previsão de término. Se algo já estiver correto, o app confirma e segue adiante.",
      steps: [
        {
          number: "01",
          title: "Diagnostica",
          text: "Identifica processador, placa de vídeo, memória, Windows, FiveM e GTA V.",
        },
        {
          number: "02",
          title: "Planeja",
          text: "Monta automaticamente o plano compatível com o perfil escolhido.",
        },
        {
          number: "03",
          title: "Protege e aplica",
          text: "Registra o estado anterior e executa apenas as mudanças necessárias.",
        },
        {
          number: "04",
          title: "Resume",
          text: "Entrega um histórico claro do que mudou, do que foi ignorado e do que pode ser desfeito.",
        },
      ],
    },
    transparency: {
      eyebrow: "CONTROLE SEM COMPLEXIDADE",
      title: "Nada escondido atrás do botão.",
      body: "O Ralven foi projetado para automatizar trabalho técnico sem transformar o Windows em uma caixa-preta.",
      items: [
        {
          title: "Snapshot antes de mudar",
          text: "As configurações reversíveis são registradas antes da aplicação para permitir rollback.",
        },
        {
          title: "Histórico legível",
          text: "Cada etapa aparece em linguagem clara, com resultado e motivo.",
        },
        {
          title: "Sem scripts remotos",
          text: "A otimização vem dentro do aplicativo; nenhum comando desconhecido é baixado para executar.",
        },
        {
          title: "Proteções preservadas",
          text: "O app não desativa Defender, firewall, UAC, Windows Update ou serviços essenciais.",
        },
      ],
      github: "Audite o projeto no GitHub",
    },
    streamers: {
      eyebrow: "PRONTO PARA QUEM JOGA E TRANSMITE",
      title: "Sua live continua sendo prioridade.",
      body: "Se OBS Studio, Streamlabs ou TikTok LIVE Studio estiver instalado ou aberto, o Ralven reconhece o ambiente e preserva ferramentas de transmissão. Ele não encerra esses processos nem altera cenas, perfis, gravações ou chats.",
      note: "A proteção para streaming faz parte dos três perfis — não é um modo separado que você precisa lembrar de ativar.",
      platforms: ["OBS Studio", "Streamlabs", "TikTok LIVE Studio"],
      safeTitle: "O que fica protegido",
      safeItems: [
        "Processos de transmissão",
        "Cenas e perfis",
        "Pastas de gravação",
        "Câmera, chat e áudio",
      ],
      honest: "O app não promete aumentar bitrate ou qualidade da live: ele evita que a otimização prejudique seu fluxo de transmissão.",
    },
    requirements: {
      eyebrow: "ANTES DE INSTALAR",
      title: "Tudo o que você precisa já vem junto.",
      body: "O instalador inclui o runtime necessário. Não é preciso procurar .NET, pacotes extras ou executar comandos manualmente.",
      systemTitle: "Requisitos",
      items: [
        "Windows 11 recomendado; Windows 10 em compatibilidade legada",
        "Sistema x64 (64 bits)",
        "Permissão de administrador nas ações de sistema",
        "Conexão apenas para atualizações e relatórios opcionais",
      ],
      installerTitle: "Instalação limpa",
      installerItems: [
        "Runtime incluído no instalador",
        "Atalho e desinstalação integrados",
        "Atualizações pela Vemryx",
        "Sem download de dependências desconhecidas",
      ],
    },
    safety: {
      eyebrow: "SEGURANÇA SEM MARKETING VAZIO",
      title: "Forte no que faz. Transparente sobre os limites.",
      body: "O Ralven usa APIs e configurações documentadas do Windows, publica o código-fonte e evita técnicas que costumam gerar bloqueios ou colocar o sistema em risco.",
      cards: [
        ["Código-fonte disponível", "Você pode auditar o código sob a licença source-available do Ralven."],
        ["Sem evasão", "O app não usa ofuscação para evitar detecção, exclusões no antivírus, injeção ou truques para esconder comportamento. A distribuição ofusca partes internas de Core e Windows; o código-fonte continua disponível para auditoria."],
        ["Hash verificável", "Confira o SHA-256 publicado na release antes de instalar."],
      ],
      warningTitle: "Sobre o SmartScreen e antivírus",
      warningBody: "Enquanto o executável não possui assinatura paga, o SmartScreen pode exibir um aviso de reputação. Nenhum projeto unsigned pode garantir zero falso positivo em todos os antivírus. Baixe somente da release oficial e confira o hash; o app não pede para desativar sua proteção.",
    },
    faq: {
      eyebrow: "PERGUNTAS FREQUENTES",
      title: "Sem letra miúda.",
      items: [
        [
          "O Ralven garante mais FPS?",
          "Não existe ganho universal: hardware, servidor, temperatura e outros fatores influenciam o resultado. O app melhora configurações relevantes, mostra uma estimativa contextual e distingue claramente estimativa de medição real.",
        ],
        [
          "Posso desfazer as alterações?",
          "Sim. As ações reversíveis geram snapshots e podem ser restauradas pelo histórico. O resumo final informa o que possui rollback.",
        ],
        [
          "O perfil Agressivo desativa a segurança do Windows?",
          "Não. Mesmo no perfil mais forte, Defender, firewall, UAC, Windows Update, arquivo de paginação e serviços essenciais são preservados.",
        ],
        [
          "Como funcionam as atualizações?",
          "O aplicativo consulta a release pública no GitHub. Quando existe uma versão estável mais recente, ele avisa e pede sua confirmação antes de baixar e instalar.",
        ],
        [
          "O aplicativo coleta meus dados?",
          "A telemetria técnica anônima vem habilitada por padrão em instalações novas e pode ser desligada a qualquer momento. Ela inclui dados técnicos allowlisted, como versão e build do Windows, modelos de CPU e GPU, faixa de RAM, perfil, ações aplicadas, estado do jogo e execução; a política pública no repositório detalha campos, finalidade, retenção e destinatários. A otimização continua acontecendo localmente.",
        ],
        [
          "Por que o SmartScreen pode alertar?",
          "Aplicativos novos e sem certificado pago ainda não têm reputação suficiente no Windows. Isso não é escondido: use sempre o link oficial e valide o hash SHA-256 da release.",
        ],
      ],
    },
    finalCta: {
      eyebrow: "Ralven",
      title: "Um clique. Um plano claro. Seu PC no controle.",
      body: "Baixe a versão estável mais recente e deixe o aplicativo decidir com segurança o que faz sentido para o seu computador.",
      download: "Baixar instalador",
      github: "Abrir GitHub",
      note: "Grátis · código-fonte disponível · Windows x64",
    },
    footer: {
      tagline: "Diagnóstico e otimização transparente para Windows e FiveM.",
      product: "Produto",
      trust: "Transparência",
      community: "Comunidade",
      discord: "Discord oficial",
      owner: "Ralven",
      rights: "© 2026 Ralven. Todos os direitos reservados.",
      noTracking: "Este site não usa cookies, analytics ou formulários.",
    },
  },
  en: {
    skip: "Skip to content",
    languageLabel: "Select language",
    navLabel: "Main navigation",
    highlightsLabel: "Highlights",
    summaryLabel: "Product summary",
    platformsLabel: "Preserved platforms",
    nav: {
      profiles: "Profiles",
      howItWorks: "How it works",
      safety: "Safety",
      faq: "FAQ",
    },
    headerDownload: "Download",
    discordLabel: "Join our official Discord",
    hero: {
      eyebrow: "RALVEN · TRANSPARENT OPTIMIZATION",
      titleStart: "More performance.",
      titleAccent: "Less complexity.",
      body: "Transparent Windows diagnostics, maintenance and optimization with clear technical decisions, real progress, rollback and specialized support for FiveM on GTA V Legacy.",
      download: "Download installer",
      github: "View code on GitHub",
      releaseNote: "Official Vemryx download · no account required",
      included: "Runtime included",
      windows: "Windows 11 recommended",
      rollback: "Rollback available",
      releaseKicker: "OFFICIAL RELEASE",
      releaseTitle: "Simple installation. No extra dependencies.",
      releaseBody: "The installer includes its required runtime and opens the latest stable version from the project’s official source.",
      releaseLink: "Open secure download",
    },
    preview: {
      label: "INTERFACE PREVIEW",
      appStatus: "System ready",
      title: "Your PC, the right plan",
      subtitle: "Local diagnosis complete",
      ringTop: "READY",
      ringBottom: "to optimize",
      profileLabel: "Selected profile",
      light: "Light",
      medium: "Balanced",
      aggressive: "Aggressive",
      recommended: "RECOMMENDED",
      progressTitle: "Preparing safe optimization",
      progressDetail: "Checking current settings…",
      detectedGpu: "CPU and GPU identified",
      detectedGame: "FiveM detected",
      local: "Local processing",
    },
    quickFacts: [
      ["01 click", "to start"],
      ["03 profiles", "with clear scopes"],
      ["Local", "optional telemetry"],
      ["Reversible", "with snapshots"],
    ],
    profiles: {
      eyebrow: "THREE PRIORITIES, ONE SIMPLE CHOICE",
      title: "Choose a profile. The app handles the rest.",
      intro: "No dozens of confusing checkboxes. Every profile uses a safe action catalog and only changes what actually needs adjustment.",
      items: [
        {
          number: "01",
          name: "Light",
          summary: "More responsiveness without sacrificing looks.",
          ideal: "Ideal for modern PCs that already run well.",
          bullets: [
            "Preserves visual quality",
            "Fixes essential Windows preferences",
            "Removes only safe temporary files",
          ],
        },
        {
          number: "02",
          name: "Balanced",
          summary: "The best balance between image and response.",
          ideal: "Recommended for most players.",
          bullets: [
            "Balances Windows, FiveM and GTA V",
            "Prioritizes the correct GPU when needed",
            "Keeps critical services and protections",
          ],
          badge: "RECOMMENDED",
        },
        {
          number: "03",
          name: "Aggressive",
          summary: "Maximum priority for performance.",
          ideal: "For entry-level or very limited hardware.",
          bullets: [
            "Reduces more nonessential visual effects",
            "Applies the strongest performance set",
            "Still preserves safety and rollback",
          ],
        },
      ],
      estimateTitle: "An honest estimate, based on your PC",
      estimateBody: "Ralven uses detected hardware and system state to contextualize each profile's potential. When no real benchmark exists, it says “gain not measured” — it never invents FPS.",
      estimateTag: "NO MADE-UP NUMBERS",
    },
    process: {
      eyebrow: "SIMPLE OUTSIDE, CAREFUL INSIDE",
      title: "You can follow every step.",
      intro: "The progress bar shows the current action, elapsed time and an estimated finish time. If something is already correct, the app confirms it and moves on.",
      steps: [
        {
          number: "01",
          title: "Diagnose",
          text: "Identifies the CPU, GPU, memory, Windows, FiveM and GTA V.",
        },
        {
          number: "02",
          title: "Plan",
          text: "Automatically builds a plan compatible with the selected profile.",
        },
        {
          number: "03",
          title: "Protect and apply",
          text: "Records the previous state and runs only the necessary changes.",
        },
        {
          number: "04",
          title: "Summarize",
          text: "Provides a clear history of what changed, what was skipped and what can be undone.",
        },
      ],
    },
    transparency: {
      eyebrow: "CONTROL WITHOUT COMPLEXITY",
      title: "Nothing hidden behind the button.",
      body: "Ralven automates technical work without turning Windows into a black box.",
      items: [
        {
          title: "Snapshot before changes",
          text: "Reversible settings are recorded before being applied so they can be rolled back.",
        },
        {
          title: "Readable history",
          text: "Every step appears in clear language, including its result and reason.",
        },
        {
          title: "No remote scripts",
          text: "Optimization ships inside the app; it does not download unknown commands to execute.",
        },
        {
          title: "Protections preserved",
          text: "The app does not disable Defender, firewall, UAC, Windows Update or essential services.",
        },
      ],
      github: "Audit the project on GitHub",
    },
    streamers: {
      eyebrow: "READY FOR PLAYERS WHO STREAM",
      title: "Your broadcast remains a priority.",
      body: "If OBS Studio, Streamlabs or TikTok LIVE Studio is installed or open, Ralven recognizes the environment and preserves streaming tools. It does not close these processes or alter scenes, profiles, recordings or chats.",
      note: "Streaming protection is part of all three profiles — not a separate mode you must remember to enable.",
      platforms: ["OBS Studio", "Streamlabs", "TikTok LIVE Studio"],
      safeTitle: "What stays protected",
      safeItems: [
        "Broadcast processes",
        "Scenes and profiles",
        "Recording folders",
        "Camera, chat and audio",
      ],
      honest: "The app does not promise better bitrate or stream quality: it prevents optimization from harming your broadcast workflow.",
    },
    requirements: {
      eyebrow: "BEFORE INSTALLING",
      title: "Everything you need is already included.",
      body: "The installer includes the required runtime. You do not need to find .NET, install extra packages or run commands manually.",
      systemTitle: "Requirements",
      items: [
        "Windows 11 recommended; legacy compatibility with Windows 10",
        "x64 (64-bit) system",
        "Administrator permission for system actions",
        "Connection only for updates and optional reports",
      ],
      installerTitle: "Clean installation",
      installerItems: [
        "Runtime included in the installer",
        "Integrated shortcut and uninstaller",
        "Updates through Vemryx",
        "No unknown dependency downloads",
      ],
    },
    safety: {
      eyebrow: "SECURITY WITHOUT EMPTY MARKETING",
      title: "Powerful where it matters. Clear about limits.",
      body: "Ralven uses documented Windows APIs and settings, publishes its source code and avoids techniques that commonly cause blocks or put the system at risk.",
      cards: [
        ["Source available", "You can inspect the code under the Ralven license."],
        ["No evasion", "No obfuscation to evade detection, antivirus exclusions, injection or tricks to hide behavior. The distribution obfuscates internal Core and Windows parts; the source code remains available for audit."],
        ["Verifiable hash", "Check the SHA-256 published with the release before installing."],
      ],
      warningTitle: "About SmartScreen and antivirus",
      warningBody: "While the executable has no paid code-signing certificate, SmartScreen may show a reputation warning. No unsigned project can guarantee zero false positives across every antivirus. Download only from the official release and verify the hash; the app never asks you to disable protection.",
    },
    faq: {
      eyebrow: "FREQUENTLY ASKED QUESTIONS",
      title: "No fine print.",
      items: [
        [
          "Does Ralven guarantee more FPS?",
          "There is no universal gain: hardware, server, temperature and other factors affect results. The app improves relevant settings, provides a contextual estimate and clearly separates estimates from real measurements.",
        ],
        [
          "Can I undo the changes?",
          "Yes. Reversible actions create snapshots and can be restored from history. The final summary identifies what supports rollback.",
        ],
        [
          "Does the Aggressive profile disable Windows security?",
          "No. Even in the strongest profile, Defender, firewall, UAC, Windows Update, pagefile and essential services remain protected.",
        ],
        [
          "How do updates work?",
          "The app checks Vemryx's signed public update feed. When a newer stable version exists, it notifies you and asks for confirmation before downloading and installing.",
        ],
        [
          "Does the application collect my data?",
          "Anonymous technical telemetry is enabled by default on new installations and can be turned off at any time. It includes allowlisted technical data such as Windows version and build, CPU and GPU models, RAM range, profile, applied actions, game state and execution; the public policy in the repository details fields, purpose, retention and recipients. Optimization stays local.",
        ],
        [
          "Why might SmartScreen show a warning?",
          "New apps without a paid certificate do not yet have enough Windows reputation. This is not hidden: always use the official link and validate the release SHA-256 hash.",
        ],
      ],
    },
    finalCta: {
      eyebrow: "Ralven",
      title: "One click. One clear plan. Your PC in control.",
      body: "Download the latest stable version and let the app safely decide what makes sense for your computer.",
      download: "Download installer",
      github: "Open GitHub",
      note: "Free · source available · Windows x64",
    },
    footer: {
      tagline: "Transparent diagnostics and optimization for Windows and FiveM.",
      product: "Product",
      trust: "Transparency",
      community: "Community",
      discord: "Official Discord",
      owner: "Ralven",
      rights: "© 2026 Ralven. All rights reserved.",
      noTracking: "This website uses no cookies, analytics or forms.",
    },
  },
} as const;

export type Copy = (typeof copy)[Language];
